New feature
tadeuasarro/private-event pull request #3
Opened 2020-09-30 21:13 UTC by tadeuasarro

###The purpose of this Pull Request is to evaluate the New Feature branch and merge it into the Develop branch

##### Added features:
- Sign up and log in users
- Create events
- Invite users to events
- Create relations between User and Event models (hosting_user)
- Create relations between User and Event models through the Invitation model (invited_user)

2020-09-30 22:11 UTC, mosesogwo requested changes
**Hello @tadeuasarro, @Shaqri... Good start on this project. Project works well with a neat interface...:+1: But some implementation changes are required::**

:point_right: In your README, add instructions on how to setup the app and how to use it.

:point_right: Your events create action should make use of the build method. i.e. `current_user.events.build(event_params)`

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/build_method_requirement.png)

:point_right: Your events index action should take care of retrieving the events into different collections for past and upcoming, and then pass the collections to the views. So you can have something like `@past_events = Event.previous_events` and `@upcoming_events = Event.upcoming_events` in the controller and then used directly in the view.


:point_right: In your user show action, use the event upcoming and past scopes to group the events instead of having an iteration manually through the collection of events. Also, have a collection for the user's created events in the show action and now retrieve this collection directly in the view. Say... `@created_events =  current_user.events`


:point_right: Add indexes for all foreign keys. See why this is necessary [here](https://semaphoreci.com/blog/2017/05/09/faster-rails-is-your-database-properly-indexed.html)
and [here](https://sqlperformance.com/2012/11/t-sql-queries/benefits-indexing-foreign-keys)

:point_right: Tests are missing. Write unit tests for model validations and associations (RSpec) and integration tests for authentication and event management (RSpec + Capybara)

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png)

:point_right: Remove commented code in Events controller

_**Kindly make these changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested:exclamation:

2020-10-02 22:21 UTC, lucasmazo32 requested changes
# Changes required :wrench:

You are doing a great job so far, and the project is looking good. 

For the project to get approved kindly implement these changes:

## Required changes:

- [ ] I can not run the tests because of a migration error. Kindly check the log below, fix the error, and submit for another code review.

### Happy coding! :computer:

## Lucas Mazo

```
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: table "events" already exists: CREATE TABLE "events" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar, "location" varchar, "date" date, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL)
$HOME/private-event/db/migrate/20200929174819_create_events.rb:3:in `change'
$HOME/private-event/bin/rails:9:in `<top (required)>'
$HOME/private-event/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: SQLite3::SQLException: table "events" already exists: CREATE TABLE "events" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar, "location" varchar, "date" date, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL)
$HOME/private-event/db/migrate/20200929174819_create_events.rb:3:in `change'
$HOME/private-event/bin/rails:9:in `<top (required)>'
$HOME/private-event/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
SQLite3::SQLException: table "events" already exists
$HOME/private-event/db/migrate/20200929174819_create_events.rb:3:in `change'
$HOME/private-event/bin/rails:9:in `<top (required)>'
$HOME/private-event/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

2020-10-05 22:01 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi Team! 👋 
You have done a great job implementing the changes requested by the previous TSE! 👍 You have also done a wonderful job with your project so far! It looks really good! 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****
* There should be no logic in your views. All of your view related logic should be encapsulated in helpers. I am sorry that this wasn't pointed out to you before but it is important that you get in the habit of using your helpers for view-related logic. Once you fix this your project should be ready to go! 🎖️ I have pointed out some view-related logic in the comments below! 

****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2020-10-05 22:01 UTC, BrittanyBlake commented on app/views/events/index.html.erb
> +      </div>
- [ ] There should be no logic in your views. View related logic can be encapsulated in view helpers **(app/helpers/*_helper.rb)**

Screenshot from the requirememnts 👇 
![Screen Shot 2020-10-05 at 11 54 11 PM](https://user-images.githubusercontent.com/48804258/95136251-12e52d80-0766-11eb-8a58-e20a700a0373.png)

You can take a look at these links for more info on where to put your logic:
- [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
- [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)

2020-10-05 22:01 UTC, BrittanyBlake commented on app/views/events/index.html.erb
> +    <% end %>
- [ ] There should be no logic in your views. View related logic can be encapsulated in view helpers **(app/helpers/*_helper.rb)**

Screenshot from the requirememnts 👇 
![Screen Shot 2020-10-05 at 11 54 11 PM](https://user-images.githubusercontent.com/48804258/95136251-12e52d80-0766-11eb-8a58-e20a700a0373.png)

You can take a look at these links for more info on where to put your logic:
- [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
- [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)

2020-10-05 22:01 UTC, BrittanyBlake commented on app/views/events/show.html.erb
> +    <% end %>
- [ ] There should be no logic in your views. View related logic can be encapsulated in view helpers **(app/helpers/*_helper.rb)**

Screenshot from the requirememnts 👇 
![Screen Shot 2020-10-05 at 11 54 11 PM](https://user-images.githubusercontent.com/48804258/95136251-12e52d80-0766-11eb-8a58-e20a700a0373.png)

You can take a look at these links for more info on where to put your logic:
- [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
- [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)

2020-10-05 22:01 UTC, BrittanyBlake commented on app/views/layouts/application.html.erb
> +    <% end %>
- [ ] There should be no logic in your views. View related logic can be encapsulated in view helpers **(app/helpers/*_helper.rb)**

Screenshot from the requirememnts 👇 
![Screen Shot 2020-10-05 at 11 54 11 PM](https://user-images.githubusercontent.com/48804258/95136251-12e52d80-0766-11eb-8a58-e20a700a0373.png)

You can take a look at these links for more info on where to put your logic:
- [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
- [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)

2020-10-05 22:01 UTC, BrittanyBlake commented on app/views/layouts/application.html.erb
> +      <% end %>
- [ ] There should be no logic in your views. View related logic can be encapsulated in view helpers **(app/helpers/*_helper.rb)**

Screenshot from the requirememnts 👇 
![Screen Shot 2020-10-05 at 11 54 11 PM](https://user-images.githubusercontent.com/48804258/95136251-12e52d80-0766-11eb-8a58-e20a700a0373.png)

You can take a look at these links for more info on where to put your logic:
- [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
- [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)

2020-10-05 22:01 UTC, BrittanyBlake commented on app/views/users/new.html.erb
> +    <% unless user_sign_in? %>
- [ ] There should be no logic in your views. View related logic can be encapsulated in view helpers **(app/helpers/*_helper.rb)**

Screenshot from the requirememnts 👇 
![Screen Shot 2020-10-05 at 11 54 11 PM](https://user-images.githubusercontent.com/48804258/95136251-12e52d80-0766-11eb-8a58-e20a700a0373.png)

You can take a look at these links for more info on where to put your logic:
- [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
- [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)

2020-10-05 22:01 UTC, BrittanyBlake commented on app/views/users/show.html.erb
> +    <% end %>
- [ ] There should be no logic in your views. View related logic can be encapsulated in view helpers **(app/helpers/*_helper.rb)**

Screenshot from the requirememnts 👇 
![Screen Shot 2020-10-05 at 11 54 11 PM](https://user-images.githubusercontent.com/48804258/95136251-12e52d80-0766-11eb-8a58-e20a700a0373.png)

You can take a look at these links for more info on where to put your logic:
- [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
- [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)

2020-10-06 15:29 UTC, tadeuasarro commented on app/views/events/index.html.erb
> +    <% end %>
This is not an actual requirement from the project

2020-10-06 16:48 UTC, MuriloRoque approved these changes
# Status: Approved :green_circle: 

### Hello @tadeuasarro and @Shaqri :wave: 

### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2022-07-26 19:53 UTC, merged